POST https://localhost:8000/api/login_check
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name" : "iphonedroid", "password": "iphonedroid"}


###

## Project
GET https://localhost:8000/api/projects
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTI0MDY3OTMsImV4cCI6MTU5MjQxMDM5Mywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.BoV25JpPp0ZBedyXu1poeAhgIjS0rCmBL-i4QwS-rNir0aq-D-iYCVR0kBaNZxNaAi06GCRtkSsLS0P77nKHuSoho0nI4kakVvQCbgxFU8L6qf23N8Hu8lVj9qpbivAryR3Z46noQcYzlkprn7kIVpK9JODkUDPqaTjAsuzOdTIRCiWCRbgu1l1pfFJ9FBx2gSEACmJVigcwokr_j_cdgNmGiWuunEPFyxnb4ee7Kmt2eWCAMi0nqfWPFK6e8eRn3_1j2PQGVCqJkmqv72hU0wmFhpeLipp9MzJVm3qGW8jKUE2LF_wBA4-ARFcmwtGOUF5kBGQJocaOhmcmcQ9DaZ6cz_92atdPQFg8hZmLCufieDwwAhMnR3Ic4jvtt1SdwlNLDpyiwUxF6RJ7w4RnfcFwPWH3Z3RYA-h8DyFsd_EuGAWe_vEkr6W62QQJtW_OCti-YT4iAPQITaJqSei8I-oQdGOAm2l38Omr2whojE6oSfglsTLUnwoDLtzWkDnt4Fj6M-X9WKBxQPFVqLgHXcuZQWOZsn6z17cKrbYHIz-3UrRMdQo6oqYaOYcd59wof8TirUSMD2TfbtKzeeYdfKMtZIDN7AxDg4Ki1d5wMk7MIU9owIwGGhBegy7Bxmvtsk-bR_IDhKh-BhPgwI1yhKrdKhpo-2XKIUxFnn-M_zU

###

## Project
POST https://localhost:8000/api/projects
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTIxNDgwMTksImV4cCI6MTU5MjE1MTYxOSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.CgNbPRRcdChmM7nPD2GWru-NciP3gxqObcl2ayemV3K1E25EO-dNQ4bZ7pKQhMDqHpWiMUNWRcjEhbOMeTqAS6tGvQjpY9IID5HXAV3R_YffKHOg1Ks7EWRoKCsoe1W_cu5AfCBV7mu0KXlbciz2NotHL5GOAIpK9qaH3LYO9n_XNupbSuSafK_ejcQsw68xMdoMRE0-g1Eg5TSVTPOPeGtkEp4-oLH42B05UgonGqSoYBL2sPO0k_dCIoLbS1ZYYkFzTDqCn9sb549gdbZmkC_skVlj-w53FAuky5Np9jEKdAr5voOWLf9jTT1Z80KZAigzIWrzc6Xlyj8rS-AXjtSfaojCaNX_Pz9pCS4GoWZTw_gm8lw1jYU9_hrYJT4m2eCms2n0Xbg-_0k76cu9S-I3I8hPjDXHNQL9ubym7U_69DCGs0xKOl7k_hfVnIsEOMMZitayWzL10crUydjIy0usfFMI422jhOOEQtdW8VS5bCfcYYLzcQMX3-oGTn1O6MNjm-Q7dTSkFPS4YLlEGC7d3psdcvYJYrGGtNgOAZDbQ63hlYe4w9N3sdq0sTFZmkFSEKQT6fU9LFhLOSPi10xL5wrwYQAY8i8cH6nvkn4mKsvGDt7nLI3BsH_SQlwd6s6Zw5IFA5NTLauqbBp9ULznY7nk9MPDZlDnCtuuZA0

{"name" : "iphonedroida", "description": "iphonedroid"}
###

## Project
GET https://localhost:8000/api/projects/2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTIxNTE3NDcsImV4cCI6MTU5MjE1NTM0Nywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.ovTFoaiwB_2NU7XwlCBjndzHII7CfAjFTbvuaLU70beDRKe2SODrUHfzNT5wK27AM0SB8cb-bPwLt_8uCLrRBQxLRMG86_9LJWSxon90mTwVod8gtR8W6s0QhTj-B1K3v7HVyBl9JS-MqmGb6pxRhfJZLlNfR09O6Fk4Vc8IJmuMJbG8vs7Ljgm1W-LcFanvyc-h_XZQrVLV3yUbI-6bWLUqqlnIaZcCbHXB5QshsgZBQk3g28gUJSsW6XbYgJK78i7lyAEuIPVyi8CLXf753CmVxs_KL-qcC2fV01A1xrAiWagUErWHS8jHD4q8_JzymXEfPMNQfxuLkIKXiv5oB8eOSBPmtk5Lb_qLp9hP_1LNtGCbAOSwkSRT2STrCZmzweJQqqCudjCfkLOg55Xn_DyJI1_Gk0SLIbvS8Q52G6x_XpEZc5fs9QH2hv49ohakscfLltAsjpf-lHt4FUQPamDDh9-VSiDvfG3HCPk5IylrCokgzLH_MBiiqg-4260hxZrHv5pf-k-rE-HX-zobg3KMEWFTbtnNqblnrzeM8teUqLB1vNmdBImVTbXMQ-uW2eoF8j4n_lkdQtpXGxeUHtsvKqdc7LyEPSz6SJq6fqOB7BMOsmaveEy8wfaGArFlaRDcdnRUgOMPyEHBLI8TglF31DKotwU-Ztxmyn2uWrU

###

## Project
PUT https://localhost:8000/api/projects/2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTIxNTE3NDcsImV4cCI6MTU5MjE1NTM0Nywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.ovTFoaiwB_2NU7XwlCBjndzHII7CfAjFTbvuaLU70beDRKe2SODrUHfzNT5wK27AM0SB8cb-bPwLt_8uCLrRBQxLRMG86_9LJWSxon90mTwVod8gtR8W6s0QhTj-B1K3v7HVyBl9JS-MqmGb6pxRhfJZLlNfR09O6Fk4Vc8IJmuMJbG8vs7Ljgm1W-LcFanvyc-h_XZQrVLV3yUbI-6bWLUqqlnIaZcCbHXB5QshsgZBQk3g28gUJSsW6XbYgJK78i7lyAEuIPVyi8CLXf753CmVxs_KL-qcC2fV01A1xrAiWagUErWHS8jHD4q8_JzymXEfPMNQfxuLkIKXiv5oB8eOSBPmtk5Lb_qLp9hP_1LNtGCbAOSwkSRT2STrCZmzweJQqqCudjCfkLOg55Xn_DyJI1_Gk0SLIbvS8Q52G6x_XpEZc5fs9QH2hv49ohakscfLltAsjpf-lHt4FUQPamDDh9-VSiDvfG3HCPk5IylrCokgzLH_MBiiqg-4260hxZrHv5pf-k-rE-HX-zobg3KMEWFTbtnNqblnrzeM8teUqLB1vNmdBImVTbXMQ-uW2eoF8j4n_lkdQtpXGxeUHtsvKqdc7LyEPSz6SJq6fqOB7BMOsmaveEy8wfaGArFlaRDcdnRUgOMPyEHBLI8TglF31DKotwU-Ztxmyn2uWrU

{"name" : "iphonedroida2", "description": "iphonedroid"}
###

## Project
DELETE https://localhost:8000/api/projects/2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTIxNTE3NDcsImV4cCI6MTU5MjE1NTM0Nywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.ovTFoaiwB_2NU7XwlCBjndzHII7CfAjFTbvuaLU70beDRKe2SODrUHfzNT5wK27AM0SB8cb-bPwLt_8uCLrRBQxLRMG86_9LJWSxon90mTwVod8gtR8W6s0QhTj-B1K3v7HVyBl9JS-MqmGb6pxRhfJZLlNfR09O6Fk4Vc8IJmuMJbG8vs7Ljgm1W-LcFanvyc-h_XZQrVLV3yUbI-6bWLUqqlnIaZcCbHXB5QshsgZBQk3g28gUJSsW6XbYgJK78i7lyAEuIPVyi8CLXf753CmVxs_KL-qcC2fV01A1xrAiWagUErWHS8jHD4q8_JzymXEfPMNQfxuLkIKXiv5oB8eOSBPmtk5Lb_qLp9hP_1LNtGCbAOSwkSRT2STrCZmzweJQqqCudjCfkLOg55Xn_DyJI1_Gk0SLIbvS8Q52G6x_XpEZc5fs9QH2hv49ohakscfLltAsjpf-lHt4FUQPamDDh9-VSiDvfG3HCPk5IylrCokgzLH_MBiiqg-4260hxZrHv5pf-k-rE-HX-zobg3KMEWFTbtnNqblnrzeM8teUqLB1vNmdBImVTbXMQ-uW2eoF8j4n_lkdQtpXGxeUHtsvKqdc7LyEPSz6SJq6fqOB7BMOsmaveEy8wfaGArFlaRDcdnRUgOMPyEHBLI8TglF31DKotwU-Ztxmyn2uWrU

<> 2020-06-14T062430.200.json
###


## Task
GET https://localhost:8000/api/tasks
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTIxNTMyNjEsImV4cCI6MTU5MjE1Njg2MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.b8gCISp75IKF9QA4gyP6_4-sbZgr1PoYmU8WknNkjImwj-IeTNqtVID8oAV6ZvmkomYp3hKSjTA5j1S_F2NsXIBu7MkpxTz8r1Y14n7Gnr60Ob5X0O7VPCLDrd7dYotUgdSYoQy6gdyh5KDd6gNz-RvmK1ko6hsmhErRsUayS1DAfJeK3_2cpEibECC4AEIb38niS2wXpraJLLLCpOj2WL4XJipKyBeqYM9gIWHoci8fF0gG8FccsFOk3d4hx-zjRYjWXj3K3K-IvkErXj0ibiStwqQ2aThxqj7p0Or60CQTBpq2WBq-H4SBUEta3QfU_eh-7FhqmJNsfp84cuZdsjyvcYrWmbJkcWqFk0Nelo2t8aAwQPtZuNvOCSB1snKZpXryjJsw5jynBvYf7a65UPi5mHOo4-rgrtcgXd8maPAqhxjkGIrIgqP-w5_57Nw0-v57rxNj9n5hbFu4KuthCoYyubz-J4CbMqzzyy_SbgXNNTWmTdSfv2EB6DPEoToopkJgWZ6k0MB4jFnJq0C0Jl8EIXfapbcqCeuksIxghioHuC9E81VuhZ54V6LcFKz19PZRJt6sbd_aA9yTyM0-89SJcxv2t5b8rYjXhldcDB4d3sBZXuFElXSytnSnctdAfLrmxIbxsOaCkoEvsn2x2ieYMmDZWtMXyrkGjg2yvaE
###

## Task
POST https://localhost:8000/api/tasks
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTIxNTMyNjEsImV4cCI6MTU5MjE1Njg2MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.b8gCISp75IKF9QA4gyP6_4-sbZgr1PoYmU8WknNkjImwj-IeTNqtVID8oAV6ZvmkomYp3hKSjTA5j1S_F2NsXIBu7MkpxTz8r1Y14n7Gnr60Ob5X0O7VPCLDrd7dYotUgdSYoQy6gdyh5KDd6gNz-RvmK1ko6hsmhErRsUayS1DAfJeK3_2cpEibECC4AEIb38niS2wXpraJLLLCpOj2WL4XJipKyBeqYM9gIWHoci8fF0gG8FccsFOk3d4hx-zjRYjWXj3K3K-IvkErXj0ibiStwqQ2aThxqj7p0Or60CQTBpq2WBq-H4SBUEta3QfU_eh-7FhqmJNsfp84cuZdsjyvcYrWmbJkcWqFk0Nelo2t8aAwQPtZuNvOCSB1snKZpXryjJsw5jynBvYf7a65UPi5mHOo4-rgrtcgXd8maPAqhxjkGIrIgqP-w5_57Nw0-v57rxNj9n5hbFu4KuthCoYyubz-J4CbMqzzyy_SbgXNNTWmTdSfv2EB6DPEoToopkJgWZ6k0MB4jFnJq0C0Jl8EIXfapbcqCeuksIxghioHuC9E81VuhZ54V6LcFKz19PZRJt6sbd_aA9yTyM0-89SJcxv2t5b8rYjXhldcDB4d3sBZXuFElXSytnSnctdAfLrmxIbxsOaCkoEvsn2x2ieYMmDZWtMXyrkGjg2yvaE

{"name" : "iphonedroida", "description": "iphonedroid", "project_id":  1}

<> 2020-06-14T070040.200.json
###

## Task
GET https://localhost:8000/api/tasks/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTIxNTMyNjEsImV4cCI6MTU5MjE1Njg2MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.b8gCISp75IKF9QA4gyP6_4-sbZgr1PoYmU8WknNkjImwj-IeTNqtVID8oAV6ZvmkomYp3hKSjTA5j1S_F2NsXIBu7MkpxTz8r1Y14n7Gnr60Ob5X0O7VPCLDrd7dYotUgdSYoQy6gdyh5KDd6gNz-RvmK1ko6hsmhErRsUayS1DAfJeK3_2cpEibECC4AEIb38niS2wXpraJLLLCpOj2WL4XJipKyBeqYM9gIWHoci8fF0gG8FccsFOk3d4hx-zjRYjWXj3K3K-IvkErXj0ibiStwqQ2aThxqj7p0Or60CQTBpq2WBq-H4SBUEta3QfU_eh-7FhqmJNsfp84cuZdsjyvcYrWmbJkcWqFk0Nelo2t8aAwQPtZuNvOCSB1snKZpXryjJsw5jynBvYf7a65UPi5mHOo4-rgrtcgXd8maPAqhxjkGIrIgqP-w5_57Nw0-v57rxNj9n5hbFu4KuthCoYyubz-J4CbMqzzyy_SbgXNNTWmTdSfv2EB6DPEoToopkJgWZ6k0MB4jFnJq0C0Jl8EIXfapbcqCeuksIxghioHuC9E81VuhZ54V6LcFKz19PZRJt6sbd_aA9yTyM0-89SJcxv2t5b8rYjXhldcDB4d3sBZXuFElXSytnSnctdAfLrmxIbxsOaCkoEvsn2x2ieYMmDZWtMXyrkGjg2yvaE
###

## Task
PUT https://localhost:8000/api/tasks/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTIxNTE3NDcsImV4cCI6MTU5MjE1NTM0Nywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.ovTFoaiwB_2NU7XwlCBjndzHII7CfAjFTbvuaLU70beDRKe2SODrUHfzNT5wK27AM0SB8cb-bPwLt_8uCLrRBQxLRMG86_9LJWSxon90mTwVod8gtR8W6s0QhTj-B1K3v7HVyBl9JS-MqmGb6pxRhfJZLlNfR09O6Fk4Vc8IJmuMJbG8vs7Ljgm1W-LcFanvyc-h_XZQrVLV3yUbI-6bWLUqqlnIaZcCbHXB5QshsgZBQk3g28gUJSsW6XbYgJK78i7lyAEuIPVyi8CLXf753CmVxs_KL-qcC2fV01A1xrAiWagUErWHS8jHD4q8_JzymXEfPMNQfxuLkIKXiv5oB8eOSBPmtk5Lb_qLp9hP_1LNtGCbAOSwkSRT2STrCZmzweJQqqCudjCfkLOg55Xn_DyJI1_Gk0SLIbvS8Q52G6x_XpEZc5fs9QH2hv49ohakscfLltAsjpf-lHt4FUQPamDDh9-VSiDvfG3HCPk5IylrCokgzLH_MBiiqg-4260hxZrHv5pf-k-rE-HX-zobg3KMEWFTbtnNqblnrzeM8teUqLB1vNmdBImVTbXMQ-uW2eoF8j4n_lkdQtpXGxeUHtsvKqdc7LyEPSz6SJq6fqOB7BMOsmaveEy8wfaGArFlaRDcdnRUgOMPyEHBLI8TglF31DKotwU-Ztxmyn2uWrU

{"name" : "iphonedroid", "description": "pep"}

<> 2020-06-14T070011.200.json
###

## Task
DELETE https://localhost:8000/api/tasks/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTIxNTE3NDcsImV4cCI6MTU5MjE1NTM0Nywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiaXBob25lZHJvaWQifQ.ovTFoaiwB_2NU7XwlCBjndzHII7CfAjFTbvuaLU70beDRKe2SODrUHfzNT5wK27AM0SB8cb-bPwLt_8uCLrRBQxLRMG86_9LJWSxon90mTwVod8gtR8W6s0QhTj-B1K3v7HVyBl9JS-MqmGb6pxRhfJZLlNfR09O6Fk4Vc8IJmuMJbG8vs7Ljgm1W-LcFanvyc-h_XZQrVLV3yUbI-6bWLUqqlnIaZcCbHXB5QshsgZBQk3g28gUJSsW6XbYgJK78i7lyAEuIPVyi8CLXf753CmVxs_KL-qcC2fV01A1xrAiWagUErWHS8jHD4q8_JzymXEfPMNQfxuLkIKXiv5oB8eOSBPmtk5Lb_qLp9hP_1LNtGCbAOSwkSRT2STrCZmzweJQqqCudjCfkLOg55Xn_DyJI1_Gk0SLIbvS8Q52G6x_XpEZc5fs9QH2hv49ohakscfLltAsjpf-lHt4FUQPamDDh9-VSiDvfG3HCPk5IylrCokgzLH_MBiiqg-4260hxZrHv5pf-k-rE-HX-zobg3KMEWFTbtnNqblnrzeM8teUqLB1vNmdBImVTbXMQ-uW2eoF8j4n_lkdQtpXGxeUHtsvKqdc7LyEPSz6SJq6fqOB7BMOsmaveEy8wfaGArFlaRDcdnRUgOMPyEHBLI8TglF31DKotwU-Ztxmyn2uWrU

<> 2020-06-14T070031.200.json
###